### ISSUE TITLE
 OptiJ Plugin Library not visible in FIJI

### ISSUE THREAD

**Issue by bobfRT1** [josephzammit90/ImageJ-Recon-Plugin-Java#3]
OptiJ.jar in plugin Folder
JAVA_VERSION="1.8.0_172"
Win10

none of the plugins are visible nor found via the command finder

**Comment by Josephzammit90** [comment]
Please forward your query to: https://github.com/pedropabloVR/ImageJ-Recon-Plugin-Java. They will assist you.
